# Generated by Django 3.2.8 on 2021-10-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BundlePrice',
            new_name='Student',
        ),
    ]
